name: static-checks
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, unlocked]
    branches:
      - main
      # - development

permissions: read-all

jobs:
  static-test:
    runs-on: ubuntu-latest
    # env:
    # NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '18.16.0'
          cache: 'npm'
      # - run: echo '//npm.pkg.github.com/:_authToken=${NPM_TOKEN}' >> .npmrc
      - name: Install dependencies
        run: npm ci
      - name: Fetch origin/main
        run: git fetch origin main
      - name: Verify Eslint
        run: npm run lint:ci
      - name: Verify Prettier
        run: npm run prettier:ci
